CREATE TABLE CM_MESSAGE
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    MSG_KEY    VARCHAR(64)   NOT NULL UNIQUE,
    TYPE       VARCHAR(16)   NOT NULL,
    MSG_VALUE  VARCHAR(1000) NOT NULL,
    DFT_VALUE  VARCHAR(1000) NOT NULL,
    REMARKS    VARCHAR(1000),
    CREATED_AT DATETIME      NOT NULL,
    CREATED_DM VARCHAR(64)   NOT NULL,
    CREATED_BY VARCHAR(64)   NOT NULL,
    UPDATED_AT DATETIME      NOT NULL,
    UPDATED_DM VARCHAR(64)   NOT NULL,
    UPDATED_BY VARCHAR(64)   NOT NULL
);