CREATE TABLE CM_MASTER_CODE
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE_TYPE       VARCHAR(200) NOT NULL,
    CODE            VARCHAR(64)  NOT NULL,
    VALUE           VARCHAR(500) NOT NULL,
    DESCRIPTION     VARCHAR(1000),
    REMARKS         VARCHAR(1000),
    IS_CONFIGURABLE CHAR(1)      NOT NULL,
    DISPLAY_ORDER   INT,
    CREATED_AT      DATETIME     NOT NULL,
    CREATED_DM      VARCHAR(64)  NOT NULL,
    CREATED_BY      VARCHAR(64)  NOT NULL,
    UPDATED_AT      DATETIME     NOT NULL,
    UPDATED_DM      VARCHAR(64)  NOT NULL,
    UPDATED_BY      VARCHAR(64)  NOT NULL

);

ALTER TABLE CM_MASTER_CODE ADD CONSTRAINT UNIQUE CM_MASTER_CODE_UK (CODE_TYPE, CODE);

INSERT INTO rainbow.CM_MASTER_CODE
(ID, CODE_TYPE, CODE, VALUE, DESCRIPTION, REMARKS, IS_CONFIGURABLE, DISPLAY_ORDER, CREATED_AT, CREATED_DM, CREATED_BY, UPDATED_AT, UPDATED_DM, UPDATED_BY)
VALUES(NULL, 'cm.boolean', 'Y', 'YES', 'Yes', NULL, 'Y', 1, NOW(), 'system', 'admin', NOW(), 'system', 'admin');
INSERT INTO rainbow.CM_MASTER_CODE
(ID, CODE_TYPE, CODE, VALUE, DESCRIPTION, REMARKS, IS_CONFIGURABLE, DISPLAY_ORDER, CREATED_AT, CREATED_DM, CREATED_BY, UPDATED_AT, UPDATED_DM, UPDATED_BY)
VALUES(NULL, 'cm.boolean', 'N', 'NO', 'No', NULL, 'Y', 2, NOW(), 'system', 'admin', NOW(), 'system', 'admin');


INSERT INTO rainbow.CM_MASTER_CODE
(ID, CODE_TYPE, CODE, VALUE, DESCRIPTION, REMARKS, IS_CONFIGURABLE, DISPLAY_ORDER, CREATED_AT, CREATED_DM, CREATED_BY, UPDATED_AT, UPDATED_DM, UPDATED_BY)
VALUES(NULL, 'cm.gender', 'F', 'Female', 'Gender Female', NULL, 'Y', 2, NOW(), 'system', 'admin', NOW(), 'system', 'admin');
INSERT INTO rainbow.CM_MASTER_CODE
(ID, CODE_TYPE, CODE, VALUE, DESCRIPTION, REMARKS, IS_CONFIGURABLE, DISPLAY_ORDER, CREATED_AT, CREATED_DM, CREATED_BY, UPDATED_AT, UPDATED_DM, UPDATED_BY)
VALUES(NULL, 'cm.gender', 'M', 'Male', 'Gender Male', NULL, 'Y', 1, NOW(), 'system', 'admin', NOW(), 'system', 'admin');
INSERT INTO rainbow.CM_MASTER_CODE
(ID, CODE_TYPE, CODE, VALUE, DESCRIPTION, REMARKS, IS_CONFIGURABLE, DISPLAY_ORDER, CREATED_AT, CREATED_DM, CREATED_BY, UPDATED_AT, UPDATED_DM, UPDATED_BY)
VALUES(NULL, 'cm.gender', '00', 'Others', 'Gender Others (Transgender)', NULL, 'Y', 3, NOW(), 'system', 'admin', NOW(), 'system', 'admin');


INSERT INTO rainbow.CM_MASTER_CODE
(ID, CODE_TYPE, CODE, VALUE, DESCRIPTION, REMARKS, IS_CONFIGURABLE, DISPLAY_ORDER, CREATED_AT, CREATED_DM, CREATED_BY, UPDATED_AT, UPDATED_DM, UPDATED_BY)
VALUES(NULL, 'cm.template.type', 'E', 'Email', 'Email Template', NULL, 'Y', 1, NOW(), 'system', 'admin', NOW(), 'system', 'admin');
INSERT INTO rainbow.CM_MASTER_CODE
(ID, CODE_TYPE, CODE, VALUE, DESCRIPTION, REMARKS, IS_CONFIGURABLE, DISPLAY_ORDER, CREATED_AT, CREATED_DM, CREATED_BY, UPDATED_AT, UPDATED_DM, UPDATED_BY)
VALUES(NULL, 'cm.template.type', 'S', 'S', 'Short Message Template', NULL, 'Y', 2, NOW(), 'system', 'admin', NOW(), 'system', 'admin');
INSERT INTO rainbow.CM_MASTER_CODE
(ID, CODE_TYPE, CODE, VALUE, DESCRIPTION, REMARKS, IS_CONFIGURABLE, DISPLAY_ORDER, CREATED_AT, CREATED_DM, CREATED_BY, UPDATED_AT, UPDATED_DM, UPDATED_BY)
VALUES(NULL, 'cm.template.type', 'D', 'Document', 'Document Template', NULL, 'Y', 3, NOW(), 'system', 'admin', NOW(), 'system', 'admin');

