CREATE TABLE CM_MASTER_CODE
(
    ID              INT PRIMARY KEY AUTO_INCREMENT,
    CODE_TYPE       VARCHAR(200) NOT NULL,
    CODE            VARCHAR(64)  NOT NULL,
    VALUE           VARCHAR(500) NOT NULL,
    DESCRIPTION     VARCHAR(1000),
    REMARKS         VARCHAR(1000),
    IS_CONFIGURABLE CHAR(1)      NOT NULL,
    DISPLAY_ORDER   INT,
    CREATED_AT      DATETIME     NOT NULL,
    CREATED_DM      VARCHAR(64)  NOT NULL,
    CREATED_BY      VARCHAR(64)  NOT NULL,
    UPDATED_AT      DATETIME     NOT NULL,
    UPDATED_DM      VARCHAR(64)  NOT NULL,
    UPDATED_BY      VARCHAR(64)  NOT NULL

);

ALTER TABLE CM_MASTER_CODE ADD CONSTRAINT UNIQUE CM_MASTER_CODE_UK (CODE_TYPE, CODE);