CREATE TABLE CM_SETTING
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    SETTING_KEY VARCHAR(64) NOT NULL UNIQUE,
    VALUE       VARCHAR(64),
    TYPE        VARCHAR(16) NOT NULL,
    DESCRIPTION VARCHAR(500),
    CREATED_AT  DATETIME    NOT NULL,
    CREATED_DM  VARCHAR(64) NOT NULL,
    CREATED_BY  VARCHAR(64) NOT NULL,
    UPDATED_AT  DATETIME    NOT NULL,
    UPDATED_DM  VARCHAR(64) NOT NULL,
    UPDATED_BY  VARCHAR(64) NOT NULL
);