CREATE TABLE CM_TEMPLATE
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME             VARCHAR(50)  NOT NULL,
    TYPE             CHAR(1)      NOT NULL,
    CATEGORY         VARCHAR(64)  NOT NULL,
    PATH             VARCHAR(200) NOT NULL UNIQUE,
    MODIFIED_CONTENT MEDIUMTEXT,
    REMARKS          VARCHAR(1000),
    RECIPIENT        VARCHAR(2000),
    CC               VARCHAR(2000),
    BCC              VARCHAR(2000),
    MOBILE_NO        VARCHAR(2000),
    IS_EDITABLE      CHAR(1)      NOT NULL,
    IS_ACTIVE        CHAR(1)      NOT NULL,
    CREATED_AT       DATETIME     NOT NULL,
    CREATED_DM       VARCHAR(64)  NOT NULL,
    CREATED_BY       VARCHAR(64)  NOT NULL,
    UPDATED_AT       DATETIME     NOT NULL,
    UPDATED_DM       VARCHAR(64)  NOT NULL,
    UPDATED_BY       VARCHAR(64)  NOT NULL
);
