CREATE TABLE USR_USER_ROLE_ASSIGN
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT         NOT NULL,
    ROLE_ID         BIGINT         NOT NULL,
    STATUS          CHAR(1)     NOT NULL,
    REMARKS         VARCHAR(500),
    EFFECTIVE_DATE  DATE,
    EXPIRATION_DATE DATE,
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_DM      VARCHAR(64) NOT NULL,
    CREATED_BY      VARCHAR(64) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_DM      VARCHAR(64) NOT NULL,
    UPDATED_BY      VARCHAR(64) NOT NULL
);

ALTER TABLE USR_USER_ROLE_ASSIGN ADD CONSTRAINT USR_USER_ROLE_ASSIGN_FK1 FOREIGN KEY (USER_ID) REFERENCES USR_USER(ID);
ALTER TABLE USR_USER_ROLE_ASSIGN ADD CONSTRAINT USR_USER_ROLE_ASSIGN_FK2 FOREIGN KEY (ROLE_ID) REFERENCES USR_ROLE(ID);