CREATE TABLE USR_USER_ROLE_ASSIGN
(
    ID              INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         INT         NOT NULL,
    STATUS          CHAR(1)     NOT NULL,
    REMARKS         VARCHAR(500),
    EFFECTIVE_DATE  DATE,
    EXPIRATION_DATE DATE,
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_DM      VARCHAR(64) NOT NULL,
    CREATED_BY      VARCHAR(64) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_DM      VARCHAR(64) NOT NULL,
    UPDATED_BY      VARCHAR(64) NOT NULL
);